api-version: "1.13"
name: TskWhitelist
main: top.tsk.TskWhitelist
version: 2019.6.30
author: tsk3
website: mc.tsktop.top
commands:
  tskwhitelist:
    description: a whitelist plugin made by tsk
    aliases:
      - twl
      - bmd
    permission: tsk.whitelist